### ISSUE TITLE
是服务不稳定吗？

### ISSUE THREAD

**Issue by ktjysu** [BurnHair/issues#65]
用的folotoy连接burn.hair中转服务，一开始测试对话还好，说两轮之后就出现错误，后台部分日志：
2024-04-28 20:42:18,239 - DEBUG - Retrying due to status code 520
2024-04-28 20:42:18,240 - DEBUG - 0 retries left
2024-04-28 20:42:18,240 - INFO - Retrying request to /audio/transcriptions in 1.744846 seconds
2024-04-28 20:42:19,985 - DEBUG - Request options: {'method': 'post', 'url': '/audio/transcriptions', 'headers': {'Content-Type': 'multipart/form-data'}, 'timeout': 5.0, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/audio/recording-6c5266e210f040a7ab911ea6640b99ac.wav'>)))], 'json_data': {'model': 'whisper-1', 'prompt': "ok. let's begin.", 'response_format': 'json'}}
2024-04-28 20:42:19,986 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2024-04-28 20:42:19,986 - DEBUG - send_request_headers.complete
2024-04-28 20:42:19,986 - DEBUG - send_request_body.started request=<Request [b'POST']>
2024-04-28 20:42:19,986 - DEBUG - send_request_body.complete
2024-04-28 20:42:19,987 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2024-04-28 20:42:21,491 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 520, b'', [(b'Date', b'Sun, 28 Apr 2024 12:42:21 GMT'), (b'Content-Type', b'text/html; charset=UTF-8'), (b'Content-Length', b'7147'), (b'Connection', b'keep-alive'), (b'Report-To', b'{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=I4myXn51nDKBXKvRBZMYo9Ufqtn7pn%2F%2Fbu03vHmEsdNM2RdWb6jSN%2BxwGYoRjgtBlS8qzXd%2BPSIVOGOqR5eZxWqdMuGpGMFXISMqJek3wT98%2FaVEmlsobzvf9fg%3D"}],"group":"cf-nel","max_age":604800}'), (b'NEL', b'{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'), (b'Strict-Transport-Security', b'max-age=15552000; includeSubDomains; preload'), (b'X-Frame-Options', b'SAMEORIGIN'), (b'Referrer-Policy', b'same-origin'), (b'Cache-Control', b'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0'), (b'Expires', b'Thu, 01 Jan 1970 00:00:01 GMT'), (b'Server', b'cloudflare'), (b'CF-RAY', b'87b721b35d9a76e3-LHR'), (b'alt-svc', b'h3=":443"; ma=86400')])
2024-04-28 20:42:21,491 - INFO - HTTP Request: POST https://burn.hair/v1/audio/transcriptions "HTTP/1.1 520 "
2024-04-28 20:42:21,491 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2024-04-28 20:42:21,492 - DEBUG - receive_response_body.complete
2024-04-28 20:42:21,492 - DEBUG - response_closed.started
2024-04-28 20:42:21,492 - DEBUG - response_closed.complete
2024-04-28 20:42:21,492 - DEBUG - HTTP Request: POST https://burn.hair/v1/audio/transcriptions "520 "
2024-04-28 20:42:21,492 - DEBUG - Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '520 ' for url 'https://burn.hair/v1/audio/transcriptions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/520

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '520 ' for url 'https://burn.hair/v1/audio/transcriptions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/520

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '520 ' for url 'https://burn.hair/v1/audio/transcriptions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/520
2024-04-28 20:42:21,493 - DEBUG - Re-raising status error

**Comment by BennyThink** [comment]
是不是因为音频文件太大了？我看错误信息是 cloudflare 520

**Comment by BennyThink** [comment]
```

one-1  | [GIN] 2024/04/28 - 12:42:15 | 20240428124214777268969PDs4mnUK | 200 |  1.005850556s |  49.x.x.x |    POST /v1/audio/transcriptions
one-1  | [GIN] 2024/04/28 - 12:42:18 | 20240428124217295585346aiYy6k8e | 200 |  788.363357ms |  49.x.x.x |    POST /v1/audio/transcriptions
one-1  | [GIN] 2024/04/28 - 12:42:21 | 20240428124220564277229HnuVmstR | 200 |  774.592472ms |  49.x.x.x |    POST /v1/audio/transcriptions
```

我看了一眼日志什么都没有， 有可能  是你请求的时候恰巧碰上了我更新的时候。再观察下看看是否频繁出现

**Comment by BennyThink** [comment]
是个 bug 有的时候音频文件如果是mp3 那么就会出现问题。现在已经修好啦， 你再试试
